import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import paymentQr from '../qr_ID1026535357986_22.09.26_1790094652_1790094652329.jpg';
import {
  Activity, ArrowDownToLine, ArrowUpRight, Bell, BookOpen, Check, ChevronRight, CircleHelp, CloudUpload,
  Code2, Copy, CreditCard, Download, FileAudio, Gauge, History, KeyRound, LayoutDashboard, Library, Link2, LockKeyhole, Menu,
  MessageCircle, MoreHorizontal, Music2, Pause as PauseIcon, Play, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Trash2, Upload,
  UserRound, Users, WandSparkles, X, Youtube, Zap
} from 'lucide-react';

const navGroups = [
  { label: 'MAIN', items: [['Dashboard', 'dashboard', LayoutDashboard]] },
  { label: 'ROBLOX', items: [['Roblox Audio', 'roblox-audio', Music2], ['Audio Library', 'library', Library], ['Roblox Uploader', 'uploader', CloudUpload], ['Upload History', 'history', History]] },
  { label: 'TOOLS', items: [['Audio Converter', 'converter', WandSparkles], ['Remix Musik', 'remix', Music2], ['YouTube Audio Converter', 'youtube', Youtube], ['Audio Optimizer', 'optimizer', Gauge], ['File Converter', 'file-converter', FileAudio]] },
  { label: 'API', items: [['B2B API', 'b2b-api', Code2], ['Developer API', 'developer-api', KeyRound], ['API Documentation', 'api-docs', BookOpen]] },
  { label: 'ACCOUNT', items: [['Payment History', 'payments', CreditCard], ['Credits', 'credits', Zap], ['Billing', 'billing', CreditCard], ['Profile', 'profile', UserRound], ['Settings', 'settings', Settings]] }
];
const recentUploads = [
  { name: 'space-radio.mp3', format: 'MP3', duration: '02:41', status: 'SUCCESS', id: '1847302958', date: 'Today, 10:42' },
  { name: 'quest-theme.wav', format: 'WAV', duration: '01:18', status: 'PROCESSING', id: '—', date: 'Yesterday' },
  { name: 'coin-pickup.ogg', format: 'OGG', duration: '00:08', status: 'FAILED', id: '—', date: 'Sep 18, 2026' }
];

function cn(...values) { return values.filter(Boolean).join(' '); }
function formatBytes(bytes) { return `${(bytes / 1024 / 1024).toFixed(2)} MB`; }

function RemixPage() {
  const location = useLocation();
  const routerNavigate = useNavigate();
  const page = location.pathname.slice(1) || 'dashboard';
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [session, setSession] = useState({ connected: false, name: 'Rivalid', userId: '—' });
  const [credits, setCredits] = useState(0);
  const [history, setHistory] = useState(recentUploads);
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [speed, setSpeed] = useState(1);
  const [previewing, setPreviewing] = useState(false);
  const [busy, setBusy] = useState(false);
  const audioRef = useRef(null);
  const canvasRef = useRef(null);
  const originalSpeed = 1;
  const robloxSpeed = Number((1 / speed).toFixed(3));

  useEffect(() => {
    if (!file || !canvasRef.current) return;
    const reader = new FileReader();
    reader.onload = async () => {
      const context = new AudioContext();
      const buffer = await context.decodeAudioData(reader.result);
      const canvas = canvasRef.current;
      const drawing = canvas.getContext('2d');
      const samples = buffer.getChannelData(0);
      drawing.clearRect(0, 0, canvas.width, canvas.height);
      drawing.strokeStyle = '#c8f76e';
      drawing.lineWidth = 1;
      drawing.beginPath();
      for (let x = 0; x < canvas.width; x += 1) {
        const start = Math.floor(x * samples.length / canvas.width);
        const end = Math.max(start + 1, Math.floor((x + 1) * samples.length / canvas.width));
        let peak = 0;
        for (let index = start; index < end; index += 1) peak = Math.max(peak, Math.abs(samples[index]));
        const y = (1 - peak) * canvas.height / 2;
        drawing.moveTo(x, canvas.height / 2 - y);
        drawing.lineTo(x, canvas.height / 2 + y);
      }
      drawing.stroke();
      context.close();
    };
    reader.readAsArrayBuffer(file);
    return () => reader.abort();
  }, [file]);

  useEffect(() => { if (audioRef.current) audioRef.current.playbackRate = speed; }, [speed]);
  useEffect(() => { setResult(null); }, [speed]);
  const chooseFile = (next) => { if (next?.type.startsWith('audio/')) { setFile(next); setResult(null); setPreviewing(false); } };
  const togglePreview = async () => { if (!audioRef.current || !file) return; audioRef.current.playbackRate = speed; if (audioRef.current.paused) { await audioRef.current.play(); setPreviewing(true); } else { audioRef.current.pause(); setPreviewing(false); } };
  const stopPreview = () => { if (!audioRef.current) return; audioRef.current.pause(); audioRef.current.currentTime = 0; setPreviewing(false); };
  const exportRemix = async () => { if (!file) return; setBusy(true); setResult(null); const form = new FormData(); form.append('audio', file); form.append('speed', String(speed)); try { const response = await fetch('/api/remix', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (error) { setResult({ error: error.message }); } finally { setBusy(false); } };
  const copyRobloxSpeed = () => navigator.clipboard.writeText(robloxSpeed.toFixed(3));
  return <section className="panel standalone-panel remix-page"><div className="panel-heading"><div><span className="eyebrow">AUDIO REMIX</span><h2>Remix Musik</h2></div><span className="safe-badge"><LockKeyhole size={12} /> LOCAL PREVIEW</span></div><label className="drop-area remix-drop"><input type="file" accept="audio/*" onChange={(event) => chooseFile(event.target.files[0])} /><div className="drop-icon"><Upload size={21} /></div><strong>{file ? file.name : 'Upload audio untuk remix'}</strong><span>MP3, WAV, OGG, M4A, FLAC hingga 100 MB</span></label>{file && <><canvas ref={canvasRef} className="remix-waveform" width="1000" height="180" /><audio ref={audioRef} src={URL.createObjectURL(file)} onEnded={() => setPreviewing(false)} /><div className="remix-controls"><label className="field-label">SPEED / KECEPATAN<input type="range" min="0.5" max="2" step="0.01" value={speed} onChange={(event) => setSpeed(Number(event.target.value))} /><strong>{speed.toFixed(2)}x</strong></label><label className="field-label">NILAI MANUAL<input type="number" min="0.5" max="2" step="0.01" value={speed} onChange={(event) => setSpeed(Math.min(2, Math.max(0.5, Number(event.target.value) || 1)))} /></label></div><div className="result-actions"><button className="primary-button" onClick={togglePreview}>{previewing ? <><PauseIcon /> Pause</> : <><Play size={16} /> Preview</>}</button><button className="secondary-button" onClick={stopPreview}><X size={15} /> Stop</button><button className="secondary-button" onClick={() => { setSpeed(1); stopPreview(); }}>Reset</button><button className="convert-button" disabled={busy} onClick={exportRemix}>{busy ? 'Remixing...' : 'Export Remix'} <ArrowUpRight size={16} /></button></div><div className="remix-metadata"><span>Original Speed: <strong>{originalSpeed.toFixed(2)}x</strong></span><span>Remix Speed: <strong>{speed.toFixed(2)}x</strong></span><span>Roblox PlaybackSpeed: <strong>{robloxSpeed.toFixed(3)}x</strong></span><button className="secondary-button" onClick={copyRobloxSpeed}>COPY ROBLOX SPEED</button><button className="secondary-button" onClick={() => { if (audioRef.current) { audioRef.current.playbackRate = robloxSpeed; audioRef.current.currentTime = 0; audioRef.current.play(); setPreviewing(true); } }}>TEST ROBLOX SPEED</button></div>{result?.error && <div className="notice-bar notice-error">{result.error}</div>}{result?.downloadUrl && <div className="result-actions"><a className="download-button" href={result.downloadUrl} download={result.name}><Download size={16} /> Download Remix</a><span className="muted-note">{result.name} · Roblox PlaybackSpeed {result.robloxPlaybackSpeed.toFixed(3)}x</span></div>}</>}</section>;
}

function App() {
  const location = useLocation();
  const routerNavigate = useNavigate();
  const page = location.pathname.slice(1) || 'dashboard';
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [session, setSession] = useState({ connected: false, name: 'Rivalid', userId: '—' });
  const [credits, setCredits] = useState(0);
  const [history, setHistory] = useState(recentUploads);
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const interactionAudioRef = useRef(null);
  const visitorIdRef = useRef(crypto.randomUUID());
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('');
  const [authUser, setAuthUser] = useState(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [online, setOnline] = useState(0);

  useEffect(() => {
    const sendPresence = () => fetch('/api/presence', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ visitorId: visitorIdRef.current }) }).then((res) => res.ok ? res.json() : null).then((data) => { if (data?.online !== undefined) setOnline(data.online); }).catch(() => {});
    sendPresence();
    const heartbeat = window.setInterval(sendPresence, 20000);
    return () => window.clearInterval(heartbeat);
  }, []);

  useEffect(() => {
    const playInteractionSound = (event) => {
      const target = event.target.closest?.('button, a, input, select, textarea, [role="button"]');
      if (!target) return;
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      if (!AudioContext) return;
      const audioContext = interactionAudioRef.current || new AudioContext();
      interactionAudioRef.current = audioContext;
      if (audioContext.state === 'suspended') audioContext.resume();
      const oscillator = audioContext.createOscillator();
      const gain = audioContext.createGain();
      const now = audioContext.currentTime;
      oscillator.type = 'sine';
      oscillator.frequency.setValueAtTime(540, now);
      oscillator.frequency.exponentialRampToValueAtTime(390, now + 0.045);
      gain.gain.setValueAtTime(0.0001, now);
      gain.gain.exponentialRampToValueAtTime(0.045, now + 0.006);
      gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.055);
      oscillator.connect(gain);
      gain.connect(audioContext.destination);
      oscillator.start(now);
      oscillator.stop(now + 0.06);
    };

    document.addEventListener('pointerdown', playInteractionSound);
    return () => document.removeEventListener('pointerdown', playInteractionSound);
  }, []);

  useEffect(() => {
    fetch('/api/auth/me', { credentials: 'include' }).then((res) => res.ok ? res.json() : null).then((data) => setAuthUser(data?.user || null)).catch(() => setAuthUser(null)).finally(() => setAuthLoading(false));
    fetch('/api/auth/roblox/me', { credentials: 'include' }).then((res) => res.ok ? res.json() : null).then((data) => { if (data?.user) setSession({ connected: true, name: data.user.displayName, userId: data.user.id, username: data.user.username }); }).catch(() => {});
    fetch('/api/session', { credentials: 'include' }).then((res) => res.json()).then((data) => { if (data.history?.length) setHistory(data.history.map((item) => ({ name: item.name, format: 'Audio', duration: '—', status: item.status === 'Uploaded' ? 'SUCCESS' : 'PROCESSING', id: item.id || '—', date: new Date(item.createdAt).toLocaleDateString() }))); }).catch(() => {});
  }, []);

  const navigate = (next) => { if (next === 'credits' || next === 'billing') { setPaymentOpen(true); return; } routerNavigate(`/${next}`); setSidebarOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const convert = async (format, quality) => {
    if (!file) return setNotice('Pilih file audio terlebih dahulu.');
    setBusy(true); setNotice('Converting audio...');
    const data = new FormData(); data.append('audio', file); data.append('format', format); data.append('quality', quality);
    try { const response = await fetch('/api/convert', { method: 'POST', body: data }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setResult(payload); setNotice('Conversion Complete'); } catch (error) { setNotice(error.message || 'Conversion failed.'); } finally { setBusy(false); }
  };
  const upload = async () => {
    if (!result) return setNotice('Convert audio dahulu.');
    if (!session.connected) return setNotice('Silakan login dengan Roblox terlebih dahulu.');
    setBusy(true); setNotice('Uploading...');
    try { const blob = await fetch(result.downloadUrl).then((res) => res.blob()); const form = new FormData(); form.append('audio', blob, result.name); form.append('displayName', result.name.replace(/\.[^.]+$/, '')); form.append('description', 'Uploaded from Rival Audio Converter'); const response = await fetch('/api/roblox/upload-audio', { method: 'POST', credentials: 'include', body: form }); const payload = await response.json(); if (!response.ok || payload.success !== true) throw new Error(payload.message || payload.error || 'Roblox sedang memproses asset.'); setResult((current) => ({ ...current, assetId: payload.assetId })); setNotice(`Upload Successful · Asset ID ${payload.assetId}`); setHistory((items) => [{ name: result.name, format: result.format.toUpperCase(), duration: '—', status: 'PROCESSING', id: payload.assetId, date: 'Just now' }, ...items]); } catch (error) { setNotice(error.message || 'Upload failed.'); } finally { setBusy(false); }
  };

  if (authLoading) return <div className="auth-loading"><div className="auth-spinner"></div><span>Preparing your workspace...</span></div>;
  if (!authUser) return <LoginScreen />;
  return <><div className="app-frame"><Sidebar page={page} navigate={navigate} open={sidebarOpen} collapsed={sidebarCollapsed} setCollapsed={setSidebarCollapsed} openPayment={() => setPaymentOpen(true)} /><div className={cn('main-column', sidebarCollapsed && 'main-expanded')}><Topbar session={{ ...session, name: authUser.name }} credits={credits} setSidebarOpen={setSidebarOpen} navigate={navigate} online={online} openPayment={() => setPaymentOpen(true)} /><main className="page-content"><WorkspacePageHeader page={page} online={online} /><PageView page={page} navigate={navigate} file={file} setFile={setFile} result={result} busy={busy} notice={notice} convert={convert} upload={upload} session={session} setSession={setSession} credits={credits} setCredits={setCredits} history={history} openPayment={() => setPaymentOpen(true)} /></main></div></div><PaymentQrModal open={paymentOpen} close={() => setPaymentOpen(false)} image={paymentQr} /></>;
}

function LoginScreen() { const [configured, setConfigured] = useState(null); useEffect(() => { fetch('/api/auth/config').then((res) => res.json()).then((data) => setConfigured(data.googleConfigured)).catch(() => setConfigured(false)); }, []); return <main className="login-screen"><div className="login-grid"></div><section className="login-card"><div className="login-brand"><span className="brand-icon"><Zap size={18} fill="currentColor" /></span><span><strong>RIVAL DEV</strong><small>CREATOR SUITE</small></span></div><div className="login-icon"><Music2 size={23} /></div><span className="eyebrow">AUDIO WORKSPACE</span><h1>Make your sound<br /><em>stand out.</em></h1><p>Sign in to convert, organize, and publish audio for your Roblox experiences.</p><button className="google-button" onClick={() => { window.location.href = '/auth/google'; }}><span>G</span>{configured === false ? 'Configure Google OAuth' : 'Continue with Google'}<ArrowUpRight size={16} /></button>{configured === false && <small className="login-setup-warning">Backend belum membaca konfigurasi Google. Restart server setelah mengisi `.env`.</small>}<small className="login-legal">By continuing, you agree to use audio you have permission to process.</small></section><div className="login-side-note"><span>01</span><strong>CREATE / CONVERT / PUBLISH</strong><p>A quieter workspace for serious Roblox creators.</p></div></main>; }

function Sidebar({ page, navigate, open, collapsed, setCollapsed, openPayment }) { return <aside className={cn('sidebar-shell', open && 'sidebar-open', collapsed && 'sidebar-collapsed')}><div className="sidebar-brand"><span className="brand-icon"><Zap size={17} fill="currentColor" /></span><div><strong>RIVAL DEV</strong><small>CREATOR SUITE</small></div></div><div className="sidebar-scroll">{navGroups.map((group) => <div className="nav-group" key={group.label}><span className="nav-group-label">{group.label}</span>{group.items.map(([label, id, Icon]) => <button title={collapsed ? label : undefined} key={id} className={cn('nav-item', page === id && 'nav-item-active')} onClick={() => navigate(id)}><Icon size={16} /><span>{label}</span>{page === id && <ChevronRight className="nav-arrow" size={14} />}</button>)}</div>)} </div><div className="upgrade-card"><Sparkles size={17} color="#c8f76e" /><strong>UPGRADE TO PREMIUM</strong><p>Unlock unlimited audio converter and more benefits.</p><button onClick={openPayment}><Sparkles size={13} /> Upgrade Now</button></div><div className="sidebar-footer"><span><CircleHelp size={14} /> Help center</span><span>v1.0.0</span></div><button className="collapse-button" onClick={() => setCollapsed(!collapsed)}><ChevronRight size={15} className={collapsed ? '' : 'collapse-icon-open'} /><span>{collapsed ? 'Expand sidebar' : 'Collapse sidebar'}</span></button></aside>; }
function Topbar({ session, credits, setSidebarOpen, navigate, online, openPayment }) { return <header className="topbar"><button className="mobile-menu" onClick={() => setSidebarOpen(true)}><Menu size={19} /></button><div className="topbar-greeting"><span>Hallo Bro /</span><strong>{session.name}</strong><i></i><small>{online} ONLINE</small></div><div className="topbar-actions"><div className="credit-pill"><Zap size={14} fill="currentColor" /> <span>{credits} credits</span><button onClick={openPayment}>Buy</button></div><a className="discord-button" href="https://discord.gg/YBFSd2vMh" target="_blank" rel="noreferrer"><MessageCircle size={16} /> Discord</a><button className="icon-action"><Bell size={17} /><b></b></button><button className="avatar-button" onClick={() => navigate('profile')}><span>R</span><strong>Rivalid</strong><ChevronRight size={14} /></button></div></header>; }
function WorkspacePageHeader({ page }) { const titles = { dashboard: ['Dashboard', 'Welcome back, Rivalid.'], 'roblox-audio': ['Roblox Audio', 'Manage your Roblox-ready audio assets.'], converter: ['Audio Converter', 'Convert and optimize audio for Roblox.'], youtube: ['YouTube Audio Converter', 'Validate a source and keep your workflow rights-aware.'], optimizer: ['Audio Optimizer', 'Clean up levels and prepare a polished audio file.'], 'file-converter': ['File Converter', 'Move between creator-friendly audio formats.'], uploader: ['Roblox Audio Uploader', 'Upload approved audio directly to your Roblox creator account.'], library: ['Audio Library', 'Your prepared audio assets in one place.'], history: ['Upload History', 'Track every conversion and Roblox upload.'], 'b2b-api': ['B2B API', 'Professional tools for teams and high-volume workflows.'], 'developer-api': ['Developer API', 'Manage credentials, credits, and request usage.'], 'api-docs': ['API Documentation', 'Build on the Rival Dev REST API.'], payments: ['Payment History', 'Review invoices and credit purchases.'], credits: ['Credits', 'Manage your conversion capacity.'], billing: ['Billing', 'Plan and payment settings.'], profile: ['Profile', 'Manage your creator identity and connected account.'], settings: ['Settings', 'Control workspace preferences and integrations.'] }; const [title, subtitle] = titles[page] || titles.converter; return <div className="page-header"><div><div className="breadcrumb">RIVAL DEV <ChevronRight size={13} /> {title.toUpperCase()}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-date"><Activity size={15} /> 86 online</div></div>; }
function PageView(props) { const { page } = props; if (page === 'dashboard') return <Dashboard navigate={props.navigate} history={props.history} />; if (page === 'converter') return <Converter {...props} />; if (page === 'youtube') return <YoutubePage navigate={props.navigate} />; if (page === 'uploader') return <Uploader {...props} />; if (page === 'library' || page === 'roblox-audio') return <LibraryPage history={props.history} />; if (page === 'history') return <HistoryPage history={props.history} />; if (page === 'optimizer') return <UtilityPage title="Audio Optimizer" icon={Gauge} description="Normalize, trim, and polish your audio before conversion." navigate={props.navigate} />; if (page === 'file-converter') return <UtilityPage title="File Converter" icon={FileAudio} description="Convert media files with the same secure processing pipeline." navigate={props.navigate} />; if (page === 'uploader') return <Uploader {...props} />; if (page === 'b2b-api') return <B2bApi navigate={props.navigate} />; if (page === 'developer-api') return <DeveloperApi navigate={props.navigate} />; if (page === 'api-docs') return <ApiDocs />; if (page === 'payments') return <PaymentHistory />; if (page === 'credits') return <CreditsPage navigate={props.navigate} />; if (page === 'billing') return <BillingPage navigate={props.navigate} />; if (page === 'profile') return <Profile session={props.session} />; return <WorkspaceSettingsPage session={props.session} setCredits={props.setCredits} />; }

function Dashboard({ navigate, history }) { return <><div className="metric-grid"><Metric icon={Zap} label="Credits" value="0" sub="Buy credits to convert" accent="lime" /><Metric icon={Music2} label="Audio uploads" value="0" sub="No uploads yet" accent="blue" /><Metric icon={WandSparkles} label="Converted" value="0" sub="Start your first conversion" accent="orange" /><Metric icon={CloudUpload} label="Roblox assets" value={history.filter((item) => item.status === 'SUCCESS').length} sub="Verified asset IDs only" accent="purple" /></div><div className="dashboard-columns"><section className="panel welcome-panel"><div><span className="eyebrow">CREATOR CONTROL CENTER</span><h2>Make your sound<br /><em>stand out.</em></h2><p>Prepare game-ready audio with a fast, focused workflow built for Roblox creators.</p><button className="primary-button" onClick={() => navigate('converter')}>Open converter <ArrowUpRight size={16} /></button></div><div className="welcome-orb"><WandSparkles size={50} /></div></section><section className="panel mini-panel"><div className="panel-title"><div><span className="eyebrow">QUICK ACTIONS</span><h3>Start a workflow</h3></div></div><div className="quick-actions"><button onClick={() => navigate('converter')}><WandSparkles size={16} /> Audio Converter <ArrowUpRight size={14} /></button><button onClick={() => navigate('uploader')}><CloudUpload size={16} /> Roblox Uploader <ArrowUpRight size={14} /></button><button onClick={() => navigate('youtube')}><Youtube size={16} /> YouTube Audio <ArrowUpRight size={14} /></button><button onClick={() => navigate('developer-api')}><Code2 size={16} /> Developer API <ArrowUpRight size={14} /></button></div></section></div></>; }
function Metric({ icon: Icon, label, value, sub, accent }) { return <div className={cn('metric-card', `metric-${accent}`)}><div className="metric-icon"><Icon size={17} /></div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>; }
function Converter({ file, setFile, result, busy, notice, convert, upload, navigate }) { const [format, setFormat] = useState('mp3'); const [quality, setQuality] = useState('192'); return <><div className="converter-topline"><div className="credits-card"><span>AVAILABLE CREDITS</span><strong>0 <small>CREDITS</small></strong><button onClick={() => navigate('settings')}>Buy Credits <ArrowUpRight size={13} /></button></div><div className="plan-card"><div><span>PLAN STATUS</span><strong>Free plan</strong></div><div className="plan-progress"><i></i></div><small>0 / 3 monthly conversions</small></div></div><div className="converter-layout"><section className="panel converter-panel"><div className="panel-heading"><div><span className="eyebrow">STEP 01 · IMPORT</span><h2>Bring your audio to life</h2></div><span className="safe-badge"><LockKeyhole size={12} /> PRIVATE</span></div><FileDrop file={file} setFile={setFile} /><div className="youtube-import"><div className="import-title"><Youtube size={17} /><div><strong>Import from YouTube</strong><small>Only use content you have permission to use.</small></div></div><div className="youtube-row"><input placeholder="YouTube URL" /><button className="secondary-button" onClick={() => navigate('youtube')}>Import Audio <Link2 size={14} /></button></div></div></section><section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">STEP 02 · OPTIMIZE</span><h2>Output settings</h2></div><WandSparkles size={18} color="#c8f76e" /></div><label className="field-label">OUTPUT FORMAT<select value={format} onChange={(event) => setFormat(event.target.value)}><option value="mp3">MP3</option><option value="wav">WAV</option><option value="ogg">OGG</option></select></label><div className="field-label">AUDIO QUALITY<div className="quality-options">{['128', '192', '320'].map((item) => <button key={item} className={cn(quality === item && 'selected')} onClick={() => setQuality(item)}>{item} <small>kbps</small></button>)}</div></div><div className="settings-foot"><span><Check size={14} /> 48 kHz stereo</span><span>Roblox optimized</span></div><button className="convert-button" disabled={!file || busy} onClick={() => convert(format, quality)}>{busy ? <RefreshCw className="spin" size={17} /> : <Zap size={17} />} {busy ? 'Converting audio...' : 'Convert Audio'} <ArrowUpRight size={17} /></button></section></div>{notice && <div className={cn('notice-bar', notice.includes('failed') || notice.includes('Pilih') || notice.includes('terlebih') ? 'notice-error' : 'notice-success')}><Activity size={16} /> {notice}</div>}{result && <ResultCard result={result} upload={upload} />}</>; }
function FileDrop({ file, setFile }) { const onFile = (next) => next?.type.startsWith('audio/') && setFile(next); return file ? <div className="file-preview"><div className="file-art"><FileAudio size={22} /></div><div><strong>{file.name}</strong><span>{formatBytes(file.size)} · {file.type || 'audio'}</span></div><audio controls src={URL.createObjectURL(file)} /><button className="icon-action" onClick={() => setFile(null)}><X size={16} /></button></div> : <label className="drop-area" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); onFile(event.dataTransfer.files[0]); }}><input type="file" accept="audio/*" onChange={(event) => onFile(event.target.files[0])} /><div className="drop-icon"><Upload size={21} /></div><strong>Drop your audio file here</strong><span>or click to browse</span><small>MP3 / WAV / OGG / FLAC</small></label>; }
function ResultCard({ result, upload }) { const [copied, setCopied] = useState(false); const copy = () => { if (result.assetId) navigator.clipboard.writeText(result.assetId); setCopied(true); setTimeout(() => setCopied(false), 1300); }; return <section className="panel result-panel"><div className="panel-heading"><div><span className="eyebrow">STEP 03 · COMPLETE</span><h2>Conversion Complete</h2></div><span className="success-label"><Check size={13} /> READY</span></div><div className="result-file"><div className="file-art"><Music2 size={21} /></div><div><strong>{result.name}</strong><span>{(result.format || '').toUpperCase()} · {formatBytes(result.size)}</span></div><audio controls src={result.downloadUrl} /></div><div className="result-actions"><a className="download-button" href={result.downloadUrl} download><ArrowDownToLine size={16} /> Download Audio</a><button className="roblox-button" onClick={upload}><CloudUpload size={16} /> Upload to Roblox</button>{result.assetId && <><button className="secondary-button" onClick={copy}>{copied ? <Check size={15} /> : <Copy size={15} />} {copied ? 'Copied' : 'Copy Asset ID'}</button><a className="secondary-button" href={`https://create.roblox.com/dashboard/creations/store/${result.assetId}/overview`} target="_blank" rel="noreferrer">Open in Roblox <ArrowUpRight size={14} /></a></>}</div></section>; }
function YoutubePage({ navigate }) { const [url, setUrl] = useState(''); const [message, setMessage] = useState(''); const validate = async () => { const res = await fetch('/api/youtube/validate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }); const data = await res.json(); setMessage(data.message || data.error); }; return <section className="panel standalone-panel youtube-page"><div className="youtube-hero"><div className="youtube-large-icon"><Youtube size={32} /></div><div><span className="eyebrow">RIGHTS-AWARE IMPORT</span><h2>Bring a permitted source into your workflow.</h2><p>We validate YouTube links only. This app never downloads DRM-protected or restricted content. Upload an audio file you are licensed to use.</p></div></div><div className="large-input-row"><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.youtube.com/watch?v=..." /><button className="primary-button" onClick={validate}>Validate URL <Check size={16} /></button></div>{message && <div className="notice-bar notice-success"><Check size={16} /> {message}</div>}<button className="text-button back-button" onClick={() => navigate('converter')}>← Back to converter</button></section>; }
function Uploader({ session, setSession }) { const connect = () => { const popup = window.open('/auth/roblox', 'robloxOAuth', 'popup,width=500,height=700'); if (!popup) window.location.href = '/auth/roblox'; }; const logout = async () => { await fetch('/api/auth/roblox/logout', { method: 'POST', credentials: 'same-origin' }); setSession({ connected: false, name: 'Rivalid', userId: '—' }); }; useEffect(() => { const receive = (event) => { if (event.origin !== window.location.origin || event.data?.type !== 'roblox-oauth') return; fetch('/api/auth/roblox/me', { credentials: 'same-origin' }).then((res) => res.json()).then((data) => { if (data.user) setSession({ connected: true, name: data.user.displayName, userId: data.user.id, username: data.user.username }); }); }; window.addEventListener('message', receive); return () => window.removeEventListener('message', receive); }, [setSession]); return <section className="panel standalone-panel uploader-page"><div className="uploader-icon"><CloudUpload size={28} /></div><span className="eyebrow">ROBLOX OPEN CLOUD</span><h2>Upload directly to Roblox</h2><p>Connect through official Roblox OAuth. Your password never touches this app, and tokens stay on the backend.</p>{session.connected ? <><div className="connected-box"><div className="avatar-large">R</div><div><strong>@{session.username || session.name}</strong><span>{session.name} · User ID {session.userId}</span></div><span className="connected-status"><i></i> Connected</span></div><button className="secondary-button" onClick={logout}>Logout Roblox</button></> : <button className="primary-button" onClick={connect}>Login with Roblox <ArrowUpRight size={16} /></button>}<div className="upload-steps"><Step number="01" label="Uploading" /><Step number="02" label="Processing" /><Step number="03" label="Moderation" /></div></section>; }
function Step({ number, label }) { return <div><span>{number}</span><strong>{label}</strong></div>; }
function LibraryPage({ history }) { const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const visible = history.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || item.status === filter.toUpperCase())); return <section className="panel standalone-panel library-panel"><div className="panel-title"><div><span className="eyebrow">YOUR ASSETS</span><h2>Audio Library</h2></div><button className="secondary-button"><Plus size={15} /> Add audio</button></div><div className="library-toolbar"><label className="search-box"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search audio files..." /></label><div className="filter-tabs">{['All', 'Uploaded', 'Processing', 'Failed'].map((item) => <button key={item} className={filter === item ? 'filter-active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Format</th><th>Duration</th><th>Size</th><th>Roblox ID</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{visible.map((item) => <tr key={`${item.name}-${item.date}`}><td><FileAudio size={15} /> {item.name}</td><td>{item.format}</td><td>{item.duration}</td><td>—</td><td className="asset-id">{item.id}</td><td><Status status={item.status} /></td><td>{item.date}</td><td><div className="row-actions"><button title="Play"><Play size={14} /></button><button title="Copy ID"><Copy size={14} /></button><button title="Download"><Download size={14} /></button><button title="Delete"><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div></section>; }
function HistoryPage({ history }) { return <section className="panel standalone-panel"><div className="panel-title"><div><span className="eyebrow">ACTIVITY LOG</span><h2>Upload History</h2></div><button className="secondary-button"><RefreshCw size={15} /> Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Audio</th><th>Type</th><th>Format</th><th>Status</th><th>Asset ID</th><th>Date</th><th>Action</th></tr></thead><tbody>{history.map((item) => <tr key={`${item.name}-${item.date}`}><td><FileAudio size={15} /> {item.name}</td><td>Roblox audio</td><td>{item.format}</td><td><Status status={item.status} /></td><td className="asset-id">{item.id}</td><td>{item.date}</td><td><button className="icon-action"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div></section>; }
function HistoryRows({ history }) { return <div className="history-rows">{history.map((item) => <div className="history-row" key={`${item.name}-${item.date}`}><div className="mini-file"><FileAudio size={15} /></div><div><strong>{item.name}</strong><small>{item.format} · {item.duration}</small></div><Status status={item.status} /><button className="icon-action"><MoreHorizontal size={16} /></button></div>)}</div>; }
function Status({ status }) { return <span className={cn('status-badge', `status-${status.toLowerCase()}`)}><i></i>{status}</span>; }
function Profile({ session }) { return <section className="profile-grid"><section className="panel profile-card"><div className="profile-avatar">R</div><h2>{session.name}</h2><p>Roblox audio creator</p><span className="profile-tag"><i></i> Active creator</span><button className="secondary-button">Edit profile</button></section><section className="panel detail-panel"><span className="eyebrow">PROFILE DETAILS</span><h2>Your creator identity</h2>{[['Display name', session.name], ['Email', 'Not connected'], ['Roblox account', session.connected ? 'Connected' : 'Not connected'], ['Member since', 'September 2026']].map(([label, value]) => <div className="detail-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section></section>; }
function WorkspaceSettingsPage({ session, setCredits }) { return <section className="settings-grid"><section className="panel detail-panel"><span className="eyebrow">PREFERENCES</span><h2>Workspace settings</h2><Setting title="Email notifications" detail="Receive updates about moderation" checked /><Setting title="Auto normalize audio" detail="Optimize levels during conversion" checked /><Setting title="Compact history" detail="Show denser activity rows" /></section><section className="panel detail-panel"><span className="eyebrow">BILLING PLACEHOLDER</span><h2>Credits & plan</h2><div className="billing-box"><Zap size={20} color="#c8f76e" /><div><strong>0 Credits</strong><span>Free plan · 3 conversions monthly</span></div></div><button className="primary-button" onClick={() => setCredits(0)}>Buy Credits <ArrowUpRight size={16} /></button><small className="muted-note">Payment gateway integration can be connected here. No fake payment is implemented.</small></section></section>; }
function SettingsPage(props) { return window.location.pathname === '/remix' ? <RemixPage /> : <WorkspaceSettingsPage {...props} />; }
function Setting({ title, detail, checked }) { const [value, setValue] = useState(checked); return <label className="setting-row"><span><strong>{title}</strong><small>{detail}</small></span><button type="button" className={cn('toggle', value && 'toggle-on')} onClick={() => setValue(!value)}><i></i></button></label>; }

function UtilityPage({ title, icon: Icon, description, navigate }) { const [file, setFile] = useState(null); const [format, setFormat] = useState('mp3'); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const isOptimizer = title === 'Audio Optimizer'; const process = async () => { if (!file) return; setBusy(true); setResult(null); const form = new FormData(); form.append('audio', file); if (!isOptimizer) form.append('format', format); try { const response = await fetch(isOptimizer ? '/api/optimize' : '/api/convert', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (error) { setResult({ error: error.message }); } finally { setBusy(false); } }; return <section className="panel standalone-panel utility-page"><div className="uploader-icon"><Icon size={28} /></div><span className="eyebrow">RIVAL DEV TOOL</span><h2>{title}</h2><p>{description}</p><label className="drop-area utility-drop"><input type="file" accept="audio/*" onChange={(event) => { setFile(event.target.files[0]); setResult(null); }} /><div className="drop-icon"><Upload size={21} /></div><strong>{file?.name || 'Choose an audio file'}</strong><span>Audio up to 100 MB</span></label>{!isOptimizer && <label className="field-label">OUTPUT FORMAT<select value={format} onChange={(event) => setFormat(event.target.value)}><option value="mp3">MP3</option><option value="wav">WAV</option><option value="ogg">OGG</option></select></label>}<button className="primary-button" disabled={!file || busy} onClick={process}>{busy ? 'Processing...' : isOptimizer ? 'Optimize Audio' : 'Convert File'} <ArrowUpRight size={16} /></button>{result?.error && <div className="notice-bar notice-error">{result.error}</div>}{result?.downloadUrl && <div className="result-actions"><a className="download-button" href={result.downloadUrl} download={result.name}><Download size={16} /> Download Result</a><audio controls src={result.downloadUrl} /></div>}<div className="tool-note"><ShieldCheck size={16} /> Processing remains on your configured backend.</div></section>; }
function ApiStatusCard({ label = 'API STATUS' }) { return <div className="api-status-card"><div><span>{label}</span><strong><i></i> ACTIVE</strong></div><Activity size={22} color="#c8f76e" /></div>; }
function B2bApi({ navigate }) { return <><div className="api-grid"><ApiStatusCard label="B2B API STATUS" /><Metric icon={Zap} label="API credits" value="0" sub="Top up when billing is connected" accent="lime" /><Metric icon={Activity} label="Requests this month" value="0" sub="No requests yet" accent="blue" /></div><section className="panel api-panel"><div className="panel-title"><div><span className="eyebrow">B2B API</span><h2>Scale your audio workflow</h2></div><button className="secondary-button" onClick={() => navigate('api-docs')}><BookOpen size={15} /> API Documentation</button></div><ApiCredential /><UsageBars /><CodeExamples /></section></>; }
function DeveloperApi({ navigate }) { return <section className="panel api-panel"><div className="panel-title"><div><span className="eyebrow">DEVELOPER API</span><h2>Keys, credits, and usage</h2></div><button className="secondary-button" onClick={() => navigate('api-docs')}><BookOpen size={15} /> Documentation</button></div><ApiStatusCard /><ApiCredential /><div className="developer-api-grid"><Metric icon={Zap} label="API credits" value="0" sub="Ready for top up" accent="lime" /><Metric icon={Activity} label="Requests" value="0" sub="Last 30 days" accent="blue" /></div><UsageBars /></section>; }
function ApiCredential() { const [revealed, setRevealed] = useState(false); return <div className="api-credential"><div><span>SECRET API KEY</span><strong>{revealed ? 'rival_live_configure_on_server' : '••••••••••••••••••••••••'}</strong></div><div><button className="secondary-button" onClick={() => setRevealed(!revealed)}>{revealed ? 'Hide' : 'Reveal'}</button><button className="secondary-button">Regenerate</button></div></div>; }
function UsageBars() { return <div className="usage-block"><div className="usage-heading"><strong>Request statistics</strong><span>Last 30 days</span></div><div className="usage-row"><span>Conversion requests</span><i><b style={{ width: '18%' }}></b></i><strong>0</strong></div><div className="usage-row"><span>Roblox uploads</span><i><b style={{ width: '7%' }}></b></i><strong>0</strong></div><div className="usage-row"><span>Asset status checks</span><i><b style={{ width: '4%' }}></b></i><strong>0</strong></div></div>; }
function CodeExamples() { const examples = { JavaScript: `const response = await fetch('/api/audio/convert', {\n  method: 'POST',\n  body: audioFormData\n});`, Python: `requests.post(\n  '/api/audio/convert',\n  files={'audio': open('sound.mp3', 'rb')}\n)`, cURL: `curl -X POST /api/audio/convert \\\n  -F "audio=@sound.mp3"` }; const [tab, setTab] = useState('JavaScript'); return <div className="code-example"><div className="code-tabs">{Object.keys(examples).map((item) => <button key={item} className={tab === item ? 'code-active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div><pre>{examples[tab]}</pre></div>; }
function ApiDocs() { const endpoints = [['POST', '/api/audio/convert', 'Convert and optimize an audio file'], ['POST', '/api/roblox/upload', 'Upload a converted asset using OAuth'], ['GET', '/api/audio/history', 'Read conversion and upload history'], ['GET', '/api/roblox/assets/:id', 'Check a Roblox asset status']]; return <section className="panel api-panel docs-panel"><div className="panel-title"><div><span className="eyebrow">REFERENCE</span><h2>API Documentation</h2></div><span className="rest-badge">REST API</span></div><p className="docs-intro">Use your server-side API key to connect Rival Dev to internal creator tools. Never expose secret keys in browser code.</p><div className="endpoint-list">{endpoints.map(([method, path, description]) => <div className="endpoint" key={path}><span className={cn('method', method.toLowerCase())}>{method}</span><code>{path}</code><span>{description}</span><ChevronRight size={15} /></div>)}</div><CodeExamples /></section>; }
function CreditsPage({ navigate }) { const packages = [['100 Credits', '$—', 'For trying the workflow'], ['500 Credits', '$—', 'For active creators'], ['1000 Credits', '$—', 'For small teams']]; return <><section className="panel credits-hero"><div><span className="eyebrow">CURRENT CREDITS</span><h2>0 <small>CREDITS</small></h2><p>Credits will be consumed by conversion workflows once billing is connected.</p></div><Zap size={39} color="#c8f76e" /></section><section className="panel package-panel"><div className="panel-title"><div><span className="eyebrow">CREDITS TOP UP</span><h2>Choose a package</h2></div><span className="muted-note">Payment gateway placeholder</span></div><div className="package-grid">{packages.map(([name, price, description]) => <div className="package-card" key={name}><Zap size={17} color="#c8f76e" /><strong>{name}</strong><b>{price}</b><p>{description}</p><button className="secondary-button" onClick={() => navigate('billing')}>Connect payment <ArrowUpRight size={14} /></button></div>)}</div></section></>; }
function BillingPage({ navigate }) { return <section className="settings-grid"><section className="panel detail-panel"><span className="eyebrow">PLAN</span><h2>Free plan</h2><div className="billing-box"><Zap size={20} color="#c8f76e" /><div><strong>0 Credits</strong><span>3 monthly conversions</span></div></div><button className="primary-button" onClick={() => navigate('credits')}>View credit packages <ArrowUpRight size={16} /></button></section><section className="panel detail-panel"><span className="eyebrow">PAYMENT METHOD</span><h2>Payment gateway</h2><p className="muted-note">No payment method is connected. This integration point is ready for Stripe, Midtrans, or another provider.</p><button className="secondary-button">Connect payment method <CreditCard size={15} /></button></section></section>; }
function PaymentHistory() { const payments = [{ invoice: '—', package: 'No purchases', amount: '—', status: 'PENDING', date: '—' }]; return <section className="panel standalone-panel"><div className="panel-title"><div><span className="eyebrow">ACCOUNT</span><h2>Payment History</h2></div><button className="secondary-button"><Download size={15} /> Export</button></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Package</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{payments.map((item) => <tr key={item.invoice}><td>{item.invoice}</td><td>{item.package}</td><td>{item.amount}</td><td><Status status={item.status} /></td><td>{item.date}</td><td><button className="icon-action"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div></section>; }

function PaymentQrModal({ open, close, image }) {
  if (!open) return null;
  return <div className="payment-modal-backdrop" onClick={close}><section className="payment-modal" onClick={(event) => event.stopPropagation()}><button className="icon-action" onClick={close} aria-label="Close payment"><X size={17} /></button><span className="eyebrow">PREMIUM PAYMENT</span><h2>Scan QR to continue</h2><p>Scan the QR code to complete your payment, then contact us with proof of payment.</p><img src={image} alt="Payment QR code" /><button className="secondary-button" onClick={close}>Close</button></section></div>;
}

function PageHeader({ page, online }) { if (page === 'remix') return <div className="page-header"><div><div className="breadcrumb">RIVAL DEV <ChevronRight size={13} /> REMIX MUSIK</div><h1>Remix Musik</h1><p>Change playback speed and export a Roblox-ready remix.</p></div><div className="header-date"><Activity size={15} /> {online} online</div></div>; return <WorkspacePageHeader page={page} online={online} />; }

export default App;
